name: niimbot_example
description: "Demonstrates how to use the niimbot plugin."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  niimbot:
    path: ../

  cupertino_icons: ^1.0.6
  file_picker: ^8.0.6
  image: ^4.2.0
  qr_flutter: ^4.1.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/
