name: niimbot
description: "Niimbot SDK"
version: 0.1.0
homepage: https://github.com/andresperezmelo/niimbot
repository: https://github.com/andresperezmelo/niimbot
issue_tracker: https://github.com/andresperezmelo/niimbot/issues

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        package: st.mnm.niimbot
        pluginClass: NiimbotPlugin
      ios:
        pluginClass: NiimbotPlugin
        #linux:
        #pluginClass: NiimbotLabelPrinterPlugin
        #macos:
        #pluginClass: NiimbotLabelPrinterPlugin
        #windows:
        #pluginClass: NiimbotLabelPrinterPluginCApi
